adapt to changes in mulle-bashfunctions

diff --git a/mulle-match b/mulle-match
--- a/mulle-match
+++ b/mulle-match
@@ -372,6 +372,12 @@ main()
 ###
 ### INIT
 ###
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    #
@@ -391,18 +397,15 @@ _init()
       then
          if [ -z "`command -v "${executablepath}"`" ]
          then
-            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
-         else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
+            _fatal "mulle-bashfunctions-env not installed"
          fi
-         exit 1
+         _fatal "Could not find libexec of mulle-bashfunctions-env"
       fi
    fi
 
-      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
-      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-
+   # shellcheck source=../../srcM/mulle-bashfunctions/src/mulle-bashfunctions-minimal.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions-minimal.sh" || \
+      _fatal "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
    if [ -z "${MULLE_MATCH_LIBEXEC_DIR}" ]
    then
       r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-match" "mulle-match-filename.sh"
diff --git a/mulle-match-to-c b/mulle-match-to-c
--- a/mulle-match-to-c
+++ b/mulle-match-to-c
@@ -359,15 +359,19 @@ write_header_file()
    r_add_line "${RVAL}" "${text_hdr}"
    text_hdr="${RVAL}"
 
-   log_verbose "Writing ${C_RESET_BOLD}${filename}"
+   log_verbose "mulle-match-to-c writes ${C_RESET_BOLD}${filename}"
    r_dirname "${filename}"
    mkdir_if_missing "${RVAL}"
-   [ -f "${filename}" ] && exekutor chmod a+w "${filename}" || return 1  
+   if [ -f "${filename}" ] 
+   then 
+      exekutor chmod a+w "${filename}" || _fatal "Can't unprotect \"${filename}\"" 
+   fi
    if ! redirect_exekutor "${filename}" printf "%s\n" "${text_hdr}"
    then
+      log_error "Failed to write \"${filename}\""
       return 1
    fi
-   exekutor chmod a-w "${filename}"
+   exekutor chmod a-w "${filename}" || log_warning "Failed to protect \"${filename}\""
 }
 
 
@@ -720,6 +724,12 @@ main()
 }
 
 
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    #
@@ -736,8 +746,7 @@ _init()
    then
       MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
       [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
-         echo "mulle-bashfunctions-env not installed" >&2 && \
-         exit 1
+         _fatal "mulle-bashfunctions-env not installed"
    fi
 
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh"  || exit 1
diff --git a/mulle-match-to-cmake b/mulle-match-to-cmake
--- a/mulle-match-to-cmake
+++ b/mulle-match-to-cmake
@@ -242,15 +242,20 @@ output_file()
    local filename="$1"
    local text="$2"
 
-   log_verbose "Writing ${C_RESET_BOLD}${filename}"
+   log_verbose "mulle-match-to-cmake writes ${C_RESET_BOLD}${filename}"
    r_dirname "${filename}"
    mkdir_if_missing "${RVAL}"
-   [ -f "${filename}" ] && exekutor chmod a+w "${filename}" || return 1  
+   if [ -f "${filename}" ] 
+   then 
+      exekutor chmod a+w "${filename}" || _fatal "Can't unprotect \"${filename}\"" 
+   fi
+
    if ! redirect_exekutor "${filename}" printf "%s\n" "${text}"
    then
+      log_error "Failed to write \"${filename}\""
       return 1
    fi
-   exekutor chmod a-w "${filename}"
+   exekutor chmod a-w "${filename}" || log_warning "Failed to protect \"${filename}\""
 }
 
 
@@ -383,8 +388,6 @@ endif()
 
 ${text_src}"
 
-   log_verbose "Writing ${C_RESET_BOLD}${MULLE_MATCH_TO_CMAKE_SOURCES_FILE}"
-
    output_file "${MULLE_MATCH_TO_CMAKE_SOURCES_FILE}" "${text_src}"
 }
 
@@ -440,8 +443,6 @@ if( MULLE_TRACE_INCLUDE)
 endif()
 
 ${text_src}"
-
-   log_verbose "Writing ${C_RESET_BOLD}${MULLE_MATCH_TO_CMAKE_RESOURCES_FILE}"
 
    output_file "${MULLE_MATCH_TO_CMAKE_RESOURCES_FILE}" "${text_src}"
 }
@@ -709,6 +710,12 @@ main()
 }
 
 
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    #
@@ -725,8 +732,7 @@ _init()
    then
       MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
       [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
-         echo "mulle-bashfunctions-env not installed" >&2 && \
-         exit 1
+         _fatal "mulle-bashfunctions-env not installed"
    fi
 
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh"  || exit 1
