* much improved callback, task, patternfile commands

diff --git a/mulle-monitor b/mulle-monitor
--- a/mulle-monitor
+++ b/mulle-monitor
@@ -32,7 +32,7 @@
 [ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
 
-MULLE_EXECUTABLE_VERSION=0.0.2
+MULLE_EXECUTABLE_VERSION=0.0.3
 MULLE_EXECUTABLE_BASHFUNCTIONS="1"
 
 
@@ -48,16 +48,16 @@ trap_fail()
 
 
 SHOWN_COMMANDS="\
+   callback       : manage callbacks
    init           : create a new project
+   patternfile    : manage patternfiles
+   task           : manage tasks
    run            : monitor files and run scripts"
 
 HIDDEN_COMMANDS="\
-   callback       : execute a callback
-   find           : find files that match
+   find           : find files that match patternfiles
    libexec-dir    : print path to mulle-monitor libexec
-   match          : match filenames
-   patternfile    : examine patternfiles
-   task           : execute a task
+   match          : match filenames against patternfiles
    uname          : mulle-monitors simplified uname(1)"
 
 
@@ -116,11 +116,11 @@ _usage()
 
    cat <<EOF
 Usage:
-   ${MULLE_EXECUTABLE_NAME} [flags] [command] [options]
+   ${MULLE_EXECUTABLE_NAME} [flags] [command]
 
-   The filesystem monitor. Call functions based on directory and
-   file changed. There are numerous possiblities to filter which
-   function is called. Functions are loaded via plugins.
+   The filesystem monitor. Invokes callbacks based on changes to files. A
+   callback may optionally invoke a task. Which callback is invoked, is based
+   on patternfiles, which are .gitignore like rule files.
 
 Flags:
 EOF
@@ -143,7 +143,7 @@ EOF
 
    cat <<EOF
 
-   Options are command specific. Use ${MULLE_EXECUTABLE_NAME} <command> -h for help.
+   Use ${MULLE_EXECUTABLE_NAME} <command> -h for topical help.
 EOF
 
    exit 1
@@ -154,125 +154,6 @@ usage()
 {
    _usage "$@" >&2
    exit 1
-}
-
-#
-# stolen from:
-# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
-# ----
-#
-_prepend_path_if_relative()
-{
-   case "$2" in
-      /*)
-         echo "$2"
-      ;;
-      *)
-         echo "$1/$2"
-      ;;
-   esac
-}
-
-
-resolve_symlinks()
-{
-   local dir_context
-   local linkpath
-
-   if linkpath="`readlink "$1"`"
-   then
-      dir_context=`dirname -- "$1"`
-      resolve_symlinks "`_prepend_path_if_relative "${dir_context}" "${linkpath}"`"
-   else
-      echo "$1"
-   fi
-}
-
-
-monitor_libexec_path()
-{
-   local executablepath="$1"
-
-   local exedir
-   local exedirpath
-   local prefix
-   local libexecpath
-
-   case "${executablepath}" in
-      \.*|/*|~*)
-      ;;
-
-      *)
-         executablepath="`command -v "${executablepath}"`"
-      ;;
-   esac
-
-   executablepath="`resolve_symlinks "${executablepath}"`"
-   exedirpath="`dirname -- "${executablepath}"`"
-   prefix="`dirname -- "${exedirpath}"`"
-   libexecpath="${prefix}/libexec/mulle-monitor"
-
-   if [ ! -x "${libexecpath}/mulle-monitor-run.sh" ]
-   then
-      libexecpath="${exedirpath}/src"
-   fi
-
-   case "$libexecpath" in
-      /*|~*)
-      ;;
-
-      *)
-         libexecpath="$PWD/$libexecpath"
-      ;;
-   esac
-
-   if [ -x "${libexecpath}/mulle-monitor-run.sh" ]
-   then
-      echo "${libexecpath}"
-   fi
-}
-
-
-_init()
-{
-   #
-   # minimal setup exit
-   #
-   if [ "$1" = "version" ]
-   then
-      echo "${MULLE_EXECUTABLE_VERSION}"
-      exit 0
-   fi
-
-   MULLE_MONITOR_LIBEXEC_DIR="`monitor_libexec_path "$0"`"
-   if [ -z "${MULLE_MONITOR_LIBEXEC_DIR}" ]
-   then
-      echo "$0 fatal error: Could not find libexec ($PWD)" >&2
-      exit 1
-   fi
-
-   #
-   # minimal setup exit
-   #
-   case "$1" in
-      "libexec-dir"|"library-path")
-         echo "${MULLE_MONITOR_LIBEXEC_DIR}"
-         exit 0
-      ;;
-   esac
-
-   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
-   [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
-      echo "mulle-bashfunctions-env not installed" >&2 && \
-      exit 1
-
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
-
-   #  set -e # more pain then gain in the end
-   #  set -u # doesn't work with my style
-
-   trap trap_fail INT
-   set -o pipefail
 }
 
 
@@ -367,6 +248,10 @@ main()
       case "$1" in
          -e)
             FLAG_OUTSIDE_ENV="YES"
+         ;;
+
+         -f)
+            MULLE_FLAG_MAGNUM_FORCE="YES"
          ;;
 
          -cd|--config-dir)
@@ -521,6 +406,70 @@ pass the -e flag"
       ;;
    esac
 }
+
+
+########
+###
+### INIT
+###
+_init()
+{
+   #
+   # minimal setup exit
+   #
+   if [ "$1" = "version" ]
+   then
+      echo "${MULLE_EXECUTABLE_VERSION}"
+      exit 0
+   fi
+
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   then
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+      then
+         if [ -z "`command -v "${executablepath}"`" ]
+         then
+             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+         else
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+         fi
+         exit 1
+      fi
+   fi
+
+      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
+      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+
+   local _libexec_dir
+
+   _get_libexec_dir "$0" "mulle-monitor" "mulle-monitor-match.sh"
+
+   MULLE_MONITOR_LIBEXEC_DIR="${_libexec_dir}"
+
+   #
+   # minimal setup exit
+   #
+   case "$1" in
+      "libexec-dir"|"library-path")
+         echo "${MULLE_MONITOR_LIBEXEC_DIR}"
+         exit 0
+      ;;
+   esac
+
+   #  set -e # more pain then gain in the end
+   #  set -u # doesn't work with my style
+
+   trap trap_fail INT
+   set -o pipefail
+
+   MULLE_ARGUMENTS="$*"
+}
+###
+### INIT
+###
+########
 
 
 _init "$@" # needs params
diff --git a/tests/05-task/run-test b/tests/05-task/run-test
--- a/tests/05-task/run-test
+++ b/tests/05-task/run-test
@@ -9,7 +9,7 @@ run_mulle_monitor()
    echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
    echo "####################################" >&2
 
-   mulle-monitor ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
+   "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
 }
 
 
diff --git a/tests/06-patternfile/run-test b/tests/06-patternfile/run-test
--- a/tests/06-patternfile/run-test
+++ b/tests/06-patternfile/run-test
@@ -9,7 +9,7 @@ run_mulle_monitor()
    echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
    echo "####################################" >&2
 
-   mulle-monitor ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
+   "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
 }
 
 
@@ -52,14 +52,14 @@ main()
    #-----------
 
    expect_mulle_monitor "00-vfl--none" -e patternfile -i list
-   expect_mulle_monitor "00-bochum--all" -e patternfile list
+   expect_mulle_monitor "00-bochum--all" -e patternfile -m list
 
    log_verbose "----- #1 PASSED -----"
 
    #-----------
 
-   expect_mulle_monitor "vfl" -e patternfile -i get "00-vfl--none"
-   expect_mulle_monitor "bochum" -e patternfile get "00-bochum--all"
+   expect_mulle_monitor "vfl" -e patternfile -i dump "00-vfl--none"
+   expect_mulle_monitor "bochum" -e patternfile dump "00-bochum--all"
 
    log_verbose "----- #2 PASSED -----"
 
diff --git a/tests/10-run-fswatch/run-test b/tests/10-run-fswatch/run-test
--- a/tests/10-run-fswatch/run-test
+++ b/tests/10-run-fswatch/run-test
@@ -9,7 +9,7 @@ run_mulle_monitor()
    echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
    echo "####################################" >&2
 
-   mulle-monitor ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
+   "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
 }
 
 
@@ -54,6 +54,8 @@ main()
    FSWATCH="${PWD}/../mock-fswatch"
    [ -x "${FSWATCH}" ] || fail "\"${FSWATCH}\" is missing"
    export FSWATCH
+
+   echo "`pwd -P`/src/foo.sh Created:Updated:IsFile" > "create-src-foo-sh-replay.txt"
 
    MULLE_FSWATCH_REPLAY_FILE="create-src-foo-sh-replay.txt" \
       expect_mulle_monitor "VfL Bochum 1848" -e run
