* split off from mulle-monitor

diff --git a/tests/06-patternfile/run-test b/tests/06-patternfile/run-test
--- a/tests/06-patternfile/run-test
+++ b/tests/06-patternfile/run-test
@@ -3,25 +3,25 @@
 [ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
 
-run_mulle_monitor()
+run_mulle_match()
 {
    echo "####################################" >&2
-   echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
+   echo mulle-match ${MULLE_MATCH_FLAGS} "$@"  >&2
    echo "####################################" >&2
 
-   "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
+   "${MULLE_MATCH}" ${MULLE_MATCH_FLAGS} "$@" || fail "\`mulle-match $*\` failed"
 }
 
 
-expect_mulle_monitor()
+expect_mulle_match()
 {
-   log_entry "expect_mulle_monitor" "$@"
+   log_entry "expect_mulle_match" "$@"
 
    local expected="$1"; shift
 
    local result
 
-   result="`run_mulle_monitor "$@"`" || exit 1
+   result="`run_mulle_match "$@"`" || exit 1
 
    if [ "${result}" != "${expected}" ]
    then
@@ -30,13 +30,13 @@ expect_mulle_monitor()
 }
 
 
-expect_failure_mulle_monitor()
+expect_failure_mulle_match()
 {
-   log_entry "expect_failure_mulle_monitor" "$@"
+   log_entry "expect_failure_mulle_match" "$@"
 
    local result
 
-   if result="`run_mulle_monitor "$@"`"
+   if result="`run_mulle_match "$@"`"
    then
       fail "Did not fail unexpectedly"
    fi
@@ -45,21 +45,21 @@ expect_failure_mulle_monitor()
 
 main()
 {
-   MULLE_MONITOR_FLAGS="$@"
+   MULLE_MATCH_FLAGS="$@"
 
    _options_mini_main "$@"
 
    #-----------
 
-   expect_mulle_monitor "00-vfl--none" -e patternfile -i list
-   expect_mulle_monitor "00-bochum--all" -e patternfile -m list
+   expect_mulle_match "00-vfl--none" -e patternfile -i list
+   expect_mulle_match "00-bochum--all" -e patternfile -m list
 
    log_verbose "----- #1 PASSED -----"
 
    #-----------
 
-   expect_mulle_monitor "vfl" -e patternfile -i dump "00-vfl--none"
-   expect_mulle_monitor "bochum" -e patternfile dump "00-bochum--all"
+   expect_mulle_match "vfl" -e patternfile -i cat "00-vfl--none"
+   expect_mulle_match "bochum" -e patternfile cat "00-bochum--all"
 
    log_verbose "----- #2 PASSED -----"
 
@@ -75,7 +75,7 @@ init()
 
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
 
-   MULLE_MONITOR="${MULLE_MONITOR:-${PWD}/../../mulle-monitor}"
+   MULLE_MATCH="${MULLE_MATCH:-${PWD}/../../mulle-match}"
 }
 
 
diff --git a/tests/11-match/run-test b/tests/11-match/run-test
--- a/tests/11-match/run-test
+++ b/tests/11-match/run-test
@@ -3,25 +3,25 @@
 [ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
 
-run_mulle_monitor()
+run_mulle_match()
 {
    echo "####################################" >&2
-   echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
+   echo mulle-match ${MULLE_MATCH_FLAGS} "$@"  >&2
    echo "####################################" >&2
 
-   "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
+   "${MULLE_MATCH}" ${MULLE_MATCH_FLAGS} "$@" || fail "\`mulle-match $*\` failed"
 }
 
 
-expect_mulle_monitor()
+expect_mulle_match()
 {
-   log_entry "expect_mulle_monitor" "$@"
+   log_entry "expect_mulle_match" "$@"
 
    local expected="$1"; shift
 
    local result
 
-   result="`run_mulle_monitor "$@"`" || exit 1
+   result="`run_mulle_match "$@"`" || exit 1
 
    if [ "${result}" != "${expected}" ]
    then
@@ -30,30 +30,32 @@ expect_mulle_monitor()
 }
 
 
-expect_failure_mulle_monitor()
+expect_failure_mulle_match()
 {
-   log_entry "expect_failure_mulle_monitor" "$@"
+   log_entry "expect_failure_mulle_match" "$@"
 
    local result
 
-   if result="`run_mulle_monitor "$@"`"
+   if result="`run_mulle_match "$@"`"
    then
       fail "Did not fail unexpectedly"
+   else
+      log_info "Failed as expected"
    fi
 }
 
 
 main()
 {
-   MULLE_MONITOR_FLAGS="$@"
+   MULLE_MATCH_FLAGS="$@"
 
    _options_mini_main "$@"
 
    #-----------
 
-   expect_mulle_monitor "type0negative-did-update" -e -md "match.d" match "a"
-   expect_mulle_monitor "type0positive-did-update" -e -md "match.d" match "b"
-   expect_failure_mulle_monitor -e -md "match.d" match "c"
+   expect_mulle_match "type0negative" -e -md "match.d" match "a"
+   expect_mulle_match "type0positive" -e -md "match.d" match "b"
+   expect_failure_mulle_match -e -md "match.d" match "c"
 
    log_verbose "----- #1 PASSED -----"
 
@@ -68,7 +70,7 @@ init()
 
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
 
-   MULLE_MONITOR="${MULLE_MONITOR:-${PWD}/../../mulle-monitor}"
+   MULLE_MATCH="${MULLE_MATCH:-${PWD}/../../mulle-match}"
 }
 
 
diff --git a/tests/12-find/run-test b/tests/12-find/run-test
--- a/tests/12-find/run-test
+++ b/tests/12-find/run-test
@@ -3,25 +3,25 @@
 [ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
 
-run_mulle_monitor()
+run_mulle_match()
 {
    echo "####################################" >&2
-   echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
+   echo mulle-match ${MULLE_MATCH_FLAGS} "$@"  >&2
    echo "####################################" >&2
 
-   "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
+   "${MULLE_MATCH}" ${MULLE_MATCH_FLAGS} "$@" || fail "\`mulle-match $*\` failed"
 }
 
 
-expect_mulle_monitor()
+expect_mulle_match()
 {
-   log_entry "expect_mulle_monitor" "$@"
+   log_entry "expect_mulle_match" "$@"
 
    local expected="$1"; shift
 
    local result
 
-   result="`run_mulle_monitor "$@"`" || exit 1
+   result="`run_mulle_match "$@"`" || exit 1
 
    if [ "${result}" != "${expected}" ]
    then
@@ -30,13 +30,13 @@ expect_mulle_monitor()
 }
 
 
-expect_failure_mulle_monitor()
+expect_failure_mulle_match()
 {
-   log_entry "expect_failure_mulle_monitor" "$@"
+   log_entry "expect_failure_mulle_match" "$@"
 
    local result
 
-   if result="`run_mulle_monitor "$@"`"
+   if result="`run_mulle_match "$@"`"
    then
       fail "Did not fail unexpectedly"
    fi
@@ -45,17 +45,17 @@ expect_failure_mulle_monitor()
 
 main()
 {
-   MULLE_MONITOR_FLAGS="$@"
+   MULLE_MATCH_FLAGS="$@"
 
    _options_mini_main "$@"
 
    #-----------
 
-   expect_mulle_monitor "a;red
+   expect_mulle_match "a;red
 z/a;red" -e -md "match.d" find -mf type0negative
 
    log_verbose "----- #1 PASSED -----"
-   expect_mulle_monitor "a;red
+   expect_mulle_match "a;red
 b;blue
 z/a;red
 z/b;blue" -e -md "match.d" find
@@ -72,7 +72,7 @@ init()
 
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
 
-   MULLE_MONITOR="${MULLE_MONITOR:-${PWD}/../../mulle-monitor}"
+   MULLE_MATCH="${MULLE_MATCH:-${PWD}/../../mulle-match}"
 }
 
 
